[package]
name = "wasmer/python-flask-server"
version = "0.1.1"
description = "wasmer/python-flask-server python application"
readme = "README.md"
 
[dependencies]
"wasmer/python" = "^3.12.6"
 
[fs]
"/src" = "./src"
"/cpython/lib/python3.12" = "./.venv/lib/python3.11"
 
[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"
 
[command.annotations.wasi]
main-args = [ # This is the command we want the python runner to run
    "-m",
    "flask",
    "--app",
    "/src/application",
    "run",
    "--no-reload",
]
env = ["PYTHONEXECUTABLE: /bin/python"] # This is the path to the python executable